### ISSUE TITLE
view.php missing correct permissions checks and mixes inline php and functions.

### ISSUE THREAD

**Issue by danmarsden** [justlorain/moodle-mod_swiftquiz#10]
the view.php files contains a mix of functions and in-line php code - ideally you should move all the functions somewhere like your locallib.php files instead of combining them all in one file, but the "swfitquiz_view()" function probably doesn't need to be inside a function - just put that code in the page as in-line php code.

also, please improve the require_login() check on this page so that it passes the $course and $cm to make sure the user has access to see the current course and cm - eg - something like this at the top of the view.php page:

```
    $id = required_param('id', PARAM_INT);
    $cm             = get_coursemodule_from_id('swiftquiz', $id, 0, false, MUST_EXIST);
    $course         = $DB->get_record('course', array('id' => $cm->course), '*', MUST_EXIST);
    require_login($course, true, $cm);
```

otherwise your view.php seems to allow users who are not in the course acess to this specfic switquiz when they should not be able to.

thanks!

**Comment by justlorain** [comment]
Hi Dan! I just check the `view.php` of latest JazzQuiz, they don't seem to do something special for this part. I think swift quiz, as a branch of jazz quiz, should be consistent in this part. What do you think?

**Comment by danmarsden** [comment]
yeah - best not to use other 3rd party plugins as an example for your version of the code - jazz quiz is likely also wrong. (but I didn't go looking at existing jazz quiz code plugin myself :-) - at the very least I need to see a require_login check on the page that prevents people that are not in the current course from being able to access the activity (like in the require_login example I gave above.)

**Comment by justlorain** [comment]
Hi Dan! I have modified it in the latest version, please let me know if there is any problem.

**Comment by danmarsden** [comment]
cool - just update the moodle.org plugins db again with your latest version and hit the request re-approval button to add it back into the review queue! :-)
