### ISSUE TITLE
Some bugs on release: 0.1.2 (Build: 2023070600)

### ISSUE THREAD

**Issue by justinhunt** [justlorain/moodle-mod_swiftquiz#11]
Line 80 of locallib.php contains a namespace declaration.
It needs to be the first line of the code, and so it throws an error . I think you can just delete it.
https://github.com/justlorain/moodle-mod_swiftquiz/blob/78bece8487ac1f11317b536c4ab9bebf43d49c6e/locallib.php#L80

And line 37 of view.php  use $DB->get_records , it should use $DB->get_record
https://github.com/justlorain/moodle-mod_swiftquiz/blob/78bece8487ac1f11317b536c4ab9bebf43d49c6e/view.php#L37

**Comment by justlorain** [comment]
Thanks for your report, PR has been merged!
