### ISSUE TITLE
Error code: ddlfieldnotexist

### ISSUE THREAD

**Issue by mattgig** [justlorain/moodle-mod_swiftquiz#13]
When I try to use SwiftQuiz with Moodle 4.2.x I get the following error message:

Debug info:
Error code: ddlfieldnotexist
Stack trace:
	• line 680 of /lib/dml/moodle_database.php: dml_exception thrown
	• line 1458 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
	• line 93 of /mod/swiftquiz/classes/improviser.php: call to moodle_database->get_records()
	• line 136 of /mod/swiftquiz/classes/improviser.php: call to mod_swiftquiz\improviser->get_improvised_question_definition()
	• line 225 of /mod/swiftquiz/classes/improviser.php: call to mod_swiftquiz\improviser->make_generic_question_definition()
	• line 282 of /mod/swiftquiz/classes/improviser.php: call to mod_swiftquiz\improviser->insert_multichoice_question_definition()
	• line 195 of /mod/swiftquiz/view.php: call to mod_swiftquiz\improviser->insert_default_improvised_question_definitions()
	• line 205 of /mod/swiftquiz/view.php: call to mod_swiftquiz\swiftquiz_view()

Is it possible that installing additional question types could cause this error?

**Comment by dinism** [comment]
Same here:
The field "category" doesn't exist in table "question".

**Comment by justlorain** [comment]
Sorry for the bug, we are checking

**Comment by justlorain** [comment]
Please try to see if the latest version (v0.1.4) is available, since our development is based on moodle3, we cannot guarantee compatibility with moodle4 and above. 
We provided the wrong compatible version information on moodle's swiftquiz page, and I'm really sorry for that 😭.
