### ISSUE TITLE
Reffering to non-exist field

### ISSUE THREAD

**Issue by lihidor** [justlorain/moodle-mod_swiftquiz#14]
hello, 
When trying to use this in moodle4.1 I'm getting an error on account of reffring to 'category' field in mdl_question table. I know that this field had moved to anothr table - mdl_question_bank_enteries. Still I do see that the module is supposed to work in moodle4.1. How can I make it work?
Thanks

**Comment by justlorain** [comment]
Please try to see if the latest version (v0.1.4) is available, since our development is based on moodle3, we cannot guarantee compatibility with moodle4 and above. 
We provided the wrong compatible version information on moodle's swiftquiz page, and I'm really sorry for that 😭.

**Comment by lihidor** [comment]
I already took the latest version, so I guess this is it...Thanks for the quick reply.
