### ISSUE TITLE
raw access to $_GET/$_POST/$_REQUEST vars not allowed

### ISSUE THREAD

**Issue by danmarsden** [justlorain/moodle-mod_swiftquiz#3]
Please use the Moodle apis "optional_param" and "required_param" for getting this data, with appropriate sanitising parameters like PARAM_INT, PARAM_TEXT and others.

Please note this is a blocker for approval in the plugins db.

**Comment by Zakkery0908** [comment]
Hi,danmarsden! When i try to solve this issue， I find that if i want to grab the parameter 'cmid'  through 'optional_param' and 'required_param'(edit.php line46-51), it will fail and the moodle page show some error(like the following pic), and i can only get the 'cmid' through &_POST/GET.

**Comment by Zakkery0908** [comment]
![341659073929_ pic](https://user-images.githubusercontent.com/75830954/181691776-9345957d-1bc9-4cb6-aa61-673049f1f4d1.jpg)

**Comment by danmarsden** [comment]
Unfortunately I don't really have time to help you work out why, but I can tell you that you need to fix it because using raw $_GET instead of the optional or required param functions is a blocker for plugins db approval - thanks!

**Comment by danmarsden** [comment]
If you can't work it out this week, add in a look to the code that isn't working here and I'll try to help more next week!

**Comment by Zakkery0908** [comment]
Hi,danmarsden! I have solved other issues further and make them better, you can check them all. But there still some  difficulty for me in this issue. And following is the pic of code (in edit.php).If i grep the cmid by optional_param or required_param , it will show some error like the above pic. So i only can get it br &_GET
![Uploading 1660811022780.png…]()

**Comment by Zakkery0908** [comment]
<img width="612" alt="1660811022780" src="https://user-images.githubusercontent.com/75830954/185348208-9fc71782-f846-47b8-8015-26ca0805191b.png">

**Comment by danmarsden** [comment]
it should work fine using $cmid = optional_param('cmid', 0, PARAM_INT);

can you give that another go and point to the code that you find isn't working when using optional_param like that?

thanks!

**Comment by Zakkery0908** [comment]
I change the code and find that error 
<img width="572" alt="1660816580737" src="https://user-images.githubusercontent.com/75830954/185367736-d4a56784-d9c5-4152-bbb8-5cdf3fd2ea83.png">
![image](https://user-images.githubusercontent.com/75830954/185367778-8def010b-bd64-4871-a94c-ea0837c0bfff.png)

**Comment by danmarsden** [comment]
ah - I see the core function "question_edit_setup" expects the cmid var to be passed to the page and you can't easily change that as it's in the core code.

you probably need to change the way the id is passed to the edit.php page and make it more like the way the mod/quiz/edit.php handles it.

for example here:
https://github.com/BinaryLorain/moodle-mod_swiftquiz/blob/23f575aa85710037d60dbdfab3adb5caf3ae2148/classes/swiftquiz.php#L260

if you pass 'cmid' => $this->cm->id in the params list it should work a bit better.

you will also likely need to change that in a few other places in your code too - so that it's passing the cmid using the var name "cmid" rather than "id" like you have now.

does that make sense?

**Comment by Zakkery0908** [comment]
Hi！ danmarseden！ i am sorry that have a so late response due to my study pressure recently，and i have one question about it， which is i know that i need to pass cmid from the front-end（instructor.js）to the edit.php,then i grap the cmid through the “optional_PARAM”，and there is a function“question_edit_setup”，and it needs us to pass cmid to it,but how can we pass cmid from edit.php to “question_edit_setup”?
There is another concern about the solution that you provided, which is in your example, i cant understand how it pass the parameter and i dont konw how to apply the same method in my issue, i find that it is pass the parameter through the creating new url, but in edit.php , can we create new url? and how can we pass the url ?

**Comment by danmarsden** [comment]
Hi @Zakkery0908 - you need to pass the variable as "cmid" to the edit.php page rather than "id" - for example, here's the change just for that specific version called from the swiftquiz class:
https://github.com/justlorain/moodle-mod_swiftquiz/commit/14ad3f3b654e91faf8d6ba99a4f3fe905b17b6d2

You would need to change other places that call edit.php to also pass the cmid to the page using the "cmid" parameter name instead of "id"

Hopefully that helps? - let me know if if not and I'll try to be clearer.

thanks!

**Comment by Zakkery0908** [comment]
Hi！danmarsden！i get your idea, and it still doesnt work. I have browsed all places that need to pass cmid and change it. There are 4 places i found: the two places that you mentioned and two places in the _swiftquiz/amd/src/edit.js_ line33 and line80

Secondly, do you mean that i only need to pass cmid rather than id, and other aspect is no problem? 

Thanks for your response !

**Comment by Zakkery0908** [comment]
Hi danmarsden!  I fixex it!!!!! i will commit the latest version to github and hope you can check it !

**Comment by Zakkery0908** [comment]
Hi danmarsden! i have fixed this issue and others (except for the first), and hope you can check! 
Thanks!

**Comment by Zakkery0908** [comment]
Hi danmarsden! i have fixed this issue and others (except for the first), and hope you can check! 
Thanks!

**Comment by danmarsden** [comment]
Great work! :-) - quick look at the code and it appears to look a lot better! - probably a good idea to clean up and remove some of the commented code when you get a chance too!

**Comment by Zakkery0908** [comment]
> Great work! :-) - quick look at the code and it appears to look a lot better! - probably a good idea to clean up and remove some of the commented code when you get a chance too!

Okay! Could you check the other issues and determine that whether have some problems? 
Thanks

**Comment by danmarsden** [comment]
If you think all the issues are sorted - just close them off, upload the zip of your updated code to the moodle.org plugins db entry and hit the "request re-approval" button on the developer zone tab - that adds it back into the review queue. Unfortunately the review queue has a bit of a backlog at the moment but I'll try to find some time to take a look. (All the plugin review team are volunteers)

thanks!
