### ISSUE TITLE
issues reported in moodle tracker

### ISSUE THREAD

**Issue by danmarsden** [justlorain/moodle-mod_swiftquiz#9]
HI team, 

not sure if you've seen the issues reported in the tracker by one of the other review team members so I've just added it below:
https://tracker.moodle.org/browse/CONTRIB-8888

Thanks for submitting the plugin - I would use it myself once it's accepted.

At the moment the plugin version uploaded is not functional, namespace definition in the middle of the file:
https://github.com/justlorain/moodle-mod_swiftquiz/blob/master/lib.php#L319

is causing fatal error:
( ! ) Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in mod/swiftquiz/lib.php on line 319

I also found some debug code:
<pre>
<?php
print_r($_POST);
?>
</pre>

left in
https://github.com/justlorain/moodle-mod_swiftquiz/blob/master/ImproviseQuestion.php#L63

once you've sorted that please upload the new version of the plugin to the plugins db and hit the request re-approval button - thanks again!

**Comment by justlorain** [comment]
Fixed in https://github.com/justlorain/moodle-mod_swiftquiz/commit/516936ea26a7876157f009d10edae1748ded5be7, thanks for report!
